apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
# - frontend
# - backend
# - ../../base/mongodb
# - ../../base/ingress.yaml
# - ../../base/secrets.yaml

resources:
- namespace.yml
- ../../base
- pv-pvc-prod.yaml

images:
- name: yuvrajsoam/chatapp-frontend
  newTag: v1.0.0
- name: yuvrajsoam/chatapp-backend
  newTag: v1.0.0

patches:
- path: backend/patch-env.yaml
- path: frontend/patch-env.yaml
- path: backend/patch-replicas.yaml
- path: frontend/patch-replicas.yaml
- path: patch-mongo-pvc-prod.yaml

namespace: chat-app-prod
