apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-prod
spec:
  storageClassName: mongo-prod # added
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/prod
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-prod
spec:
  storageClassName: mongo-prod # added
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mongodb-pv-prod
