# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongodb-pvc
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi

# PV fields like hostPath.path are immutable — patching them causes:

# Forbidden: spec.persistentvolumesource is immutable


# So overlay must create separate PV/PVC resources.