# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongodb-pv
# spec:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 5Gi
#   hostPath:
#     path: /data

# PV fields like hostPath.path are immutable — patching them causes:

# Forbidden: spec.persistentvolumesource is immutable


# So overlay must create separate PV/PVC resources.