apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: chatapp-frontend
spec:
  selector:
    matchLabels:
      app: chatapp-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: chatapp-frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: yuvrajsoam/chatapp-frontend
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
