apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: chat-prod-updater
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "chat-prod"
      images:
        - alias: "backend"
          imageName: "yuvrajsoam/chatapp-backend"
          commonUpdateSettings:
            updateStrategy: "semver"
          kustomizeSettings:
            kustomizationPath: "k8s/overlays/prod"
            newTagFieldName: "newTag"
        - alias: "frontend"
          imageName: "yuvrajsoam/chatapp-frontend"
          commonUpdateSettings:
            updateStrategy: "semver"
          kustomizeSettings:
            kustomizationPath: "k8s/overlays/prod"
            newTagFieldName: "newTag"
      git:
        writeBackMethod: "git"
        branch: "main"
        credentials:
          secretRef:
            name: argocd-image-updater-git-creds
            namespace: argocd
