apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chatapp-appset
  namespace: argocd
annotations:
  argocd-image-updater.argoproj.io/image-list: |
    frontend=yuvrajsoam/chatapp-frontend
    backend=yuvrajsoam/chatapp-backend
  argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-image-updater-git-creds
  argocd-image-updater.argoproj.io/frontend.update-strategy: semver
  argocd-image-updater.argoproj.io/backend.update-strategy: semver
  argocd-image-updater.argoproj.io/frontend.kustomize.image-name: frontend
  argocd-image-updater.argoproj.io/backend.kustomize.image-name: backend

spec:
  generators:
  - list:
      elements:
      - env: dev
        path: k8s/overlays/dev
        namespace: chat-app
      - env: prod
        path: k8s/overlays/prod
        namespace: chat-app-prod

  template:
    metadata:
      name: chat-{{env}}
    spec:
      project: chatapp-project
      source:
        repoURL: https://github.com/YuvrajSoam/Argo-k8sproject.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
