apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secret
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjME1qTTRNamN3TUN3aWFXRjBJam94TnpReU16Z3lOekF3ZlEuX1g2clRVeHZKU3AxeDdQMGhpc3E3YWtaOVJHMnFkT3Baa05rTGFBTWR0aw==
