# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
# - frontend
# - backend
# - ../../base/mongodb
# - ../../base/ingress.yaml
# - ../../base/secrets.yaml

# namespace: chat-app

resources:
- ../../base

patches:
- path: backend/patch-env.yaml
- path: frontend/patch-env.yaml
- path: patch-pv-dev.yaml # patch PV name/path for dev
- path: patch-pvc-dev.yaml # patch PVC name for dev

namespace: chat-app
