# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
# - frontend
# - backend
# - ../../base/mongodb
# - ../../base/ingress.yaml
# - ../../base/secrets.yaml

# namespace: chat-app

resources:
- ../../base
- pv-pvc-dev.yaml

patches:
- path: backend/patch-env.yaml
- path: frontend/patch-env.yaml
- path: patch-mongo-pvc-dev.yaml

namespace: chat-app
