apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  template:
    spec:
      containers:
      - name: chat-app-mongodb
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongodb-pvc-dev
