apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  template:
    spec:
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongodb-pvc-dev
