apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-dev
spec:
  storageClassName: mongo-dev # ADD THIS
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-dev
spec:
  storageClassName: mongo-dev # ADD THIS
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mongodb-pv-dev
